# 定义接收数据的协议
# 文档 https://opentelemetry.io/docs/collector/configuration/#receivers
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  prometheus:
    config:
      # The `scrape_configs` section pertains to the Prometheus `scrape_configs`
      # configuration block.
      # See https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config
      scrape_configs:
        # Scrape Mimir metrics.
        - job_name: 'mimir'
          static_configs:
            - targets: [ 'mimir:9009' ]
              labels:
                service: 'mimir'
                group: 'infrastructure'
        # Scrape Loki metrics.
        - job_name: 'loki'
          static_configs:
            - targets: [ 'loki:3100' ]
              labels:
                service: 'loki'
                group: 'infrastructure'
        # Scrape Tempo metrics.
        - job_name: 'tempo'
          static_configs:
            - targets: ['tempo:3200']
              labels:
                service: 'tempo'
                group: 'infrastructure'
        # Scrape Grafana metrics.
        - job_name: 'grafana'
          static_configs:
            - targets: ['grafana:3000']
              labels:
                service: 'grafana'
                group: 'infrastructure'

        - job_name: 'order-service'
          scrape_interval: 2s
          static_configs:
            - targets: ['order-service:7071']
              labels:
                service: 'order-service'
                group: 'service'
        - job_name: 'user-service'
          scrape_interval: 2s
          static_configs:
            - targets: [ 'user-service:7072' ]
              labels:
                service: 'user-service'
                group: 'service'
        - job_name: 'product-service'
          scrape_interval: 2s
          static_configs:
            - targets: [ 'product-service:7073' ]
              labels:
                service: 'product-service'
                group: 'service'

# Define processors to process received data.
# See https://opentelemetry.io/docs/collector/configuration/#processors
processors:
  # Use the in-built `batch` processor to batch up data before writing it for export.
  # Use the default values for it.
  batch:

  # 尾部采样器
  # see https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor
  tail_sampling:
    decision_wait: 30s    # 在做出采样决定前，从轨迹的第一个跨度开始的等待时间，默认30s
    num_traces: 50000 # 内存中保存的跟踪次数。默认50000
    expected_new_traces_per_sec: 0 # 新轨迹的预期数量（有助于分配数据结构） 默认0
    # 多个策略之间是 OR 的关系，只要满足一个就行，如果想要 and 关系，则使用 and 策略，具体看文档
    # 匹配将导致断路，一个匹配成功后不会再判断是否匹配其他策略
    policies: [
      # This policy defines that traces that include spans that contain errors should be kept.
      {
        name: sample-erroring-traces,           # Name of the policy.
        type: status_code,                      # The type must match the type of policy to be used.
        status_code: { status_codes: [ERROR] }  # Only sample traces which have a span containing an error.
      },
      # This policy defines that traces that are over 200ms should be sampled.
      {
        name: sample-long-traces,               # Name of the policy.
        type: latency,                          # The type must match the type of policy to be used.
        latency: { threshold_ms: 200 },         # Only sample traces which are longer than 200ms in duration.
      },
    ]


# 连接器是一种既是导出器又是接收器的组件。顾名思义，连接器将连接两个管道：它作为一个导出器接收一个管道的数据，
# 作为一个接收器在另一个管道的开始处发送数据。它可以消费和发送相同数据类型的数据，也可以是不同的数据类型。
# 连接器可以生成并发送汇总的数据，也可以简单地复制或路由数据。
# See https://opentelemetry.io/docs/collector/configuration/#connectors
connectors:
  # The spanmetrics connector is used to output span metrics based on received trace spans.
  spanmetrics:
    namespace: traces.spanmetrics   # Prefix all metrics with `traces.spanmetrics` (this becomes `traces_spanmetrics`).
    # Determine the type of histogram to use for span metrics.
    histogram:
      explicit:                     # Explicit histograms have pre-defined bucket sizes (use default here).
    # Defines additional label dimensions of the metrics from trace span attributes present.
    dimensions:
      - name: http.method
      - name: http.target
      - name: http.status_code
      - name: service.version
    # Ensure exemplars are enabled and sent to the metrics store.
    exemplars:
      enabled: true

  # The servicegraph connector is used to output service node metrics based on received trace spans.
  servicegraph:
      # Defines which exporter the processor will write metrics to.
      metrics_exporter: prometheusremotewrite
      # Defines additional label dimensions of the metrics from trace span attributes present.
      store:                      # Configuration for the in-memory store.
        ttl: 2s                   # Time to wait for an edge to be completed.
        max_items: 200            # Number of edges that will be stored in the storeMap.
      cache_loop: 2m              # The timeout used to clean the cache periodically.
      store_expiration_loop: 10s  # The timeout used to expire old entries from the store periodically.
      # Virtual node peer attributes allow server nodes to be generated where instrumentation isn't present (eg. where
      # service client calls remotely to a service that does not include instrumentation).
      # Service nodes/edges will be generated for any attribute defined.
      virtual_node_peer_attributes:
        - db.name

exporters:
  debug:
    verbosity: detailed
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  prometheusremotewrite:
    endpoint: http://mimir:9009/api/v1/push
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      # processors: [batch]
      processors: [servicegraph, batch]
      # processors: [tail_sampling, batch]
      # exporters: [otlp/tempo, debug]
      exporters: [otlp/tempo, spanmetrics]
    metrics:
      receivers: [prometheus]
      # processors: [batch]
      processors: [spanmetrics,batch]
      exporters: [prometheusremotewrite]
    # logs:
    #   receivers: [otlp]
    #   exporters: [debug]
