version: "3"
services:
  order-service:
    build: order-service/
    ports:
      - "7071:7071"
    volumes:
      - ./logs:/root/logs
  product-service:
    build: product-service/
    volumes:
      - ./logs:/root/logs
    # ports:
    #   - "7073:7073"
  user-service:
    build: user-service/
    volumes:
      - ./logs:/root/logs
    # ports:
    #   - "7072:7072"
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    ports:
      - "12347:12345"
      - "12348:12348"
      - "6832:6832"
      - "55679:55679"
      - "4318:4318"
    volumes:
      - ./collector-config.yml:/etc/otel-collector-config.yml
    command: ["--config=/etc/otel-collector-config.yml"]

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
      # - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin

  mimir:
    image: grafana/mimir:2.11.0
    command: [ "-ingester.native-histograms-ingestion-enabled=true", "-config.file=/etc/mimir.yaml" ]
    ports:
      - "9009:9009"
    volumes:
      - "./mimir.yaml:/etc/mimir.yaml"

  grafana:
    image: grafana/grafana:10.2.2
    volumes:
      # - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - "./grafana/definitions:/var/lib/grafana/dashboards"
      - "./grafana/provisioning:/etc/grafana/provisioning"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph traceqlSearch correlations traceQLStreaming metricsSummary traceqlEditor
      # todo 功能
    ports:
      - "3000:3000"

#  prometheus:
#    image: prom/prometheus:latest
#    command:
#      - --config.file=/etc/prometheus.yaml
#      - --web.enable-remote-write-receiver
#      - --enable-feature=exemplar-storage
#    volumes:
#      - ./prometheus.yaml:/etc/prometheus.yaml
#    ports:
#      - "9090:9090"

  # The Loki service stores logs sent to it, and takes queries from Grafana
  # to visualise those logs.
  loki:
    image: grafana/loki:2.9.3
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.9.3
    ports:
      - "9080:9080"
    volumes:
      - ./promtail-config.yaml:/etc/conf/promtail-config.yaml
      - ./logs:/home/logs
    command: ["-config.file=/etc/conf/promtail-config.yaml"]
