server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: midway-logs
    pipeline_stages:
      - json:
          expressions:
            level: LEVEL
            traceId: traceId
            message: message
            project: project
      - labels:
          level: null
          traceId: null
          project: null
      - output:
          source: message
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /home/logs/**/*-app.log
